
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

Library UNISIM;
use UNISIM.vcomponents.all;

entity ov7670_top is
    Port (
        clk100        : in    STD_LOGIC;
        axi_resend : in STD_LOGIC;
        OV7670_SIOC  : out   STD_LOGIC;
        OV7670_SIOD  : inout STD_LOGIC;
        OV7670_RESET : out   STD_LOGIC;
        OV7670_PWDN  : out   STD_LOGIC;
        OV7670_VSYNC : in    STD_LOGIC;
        OV7670_HREF  : in    STD_LOGIC;
        OV7670_PCLK  : in    STD_LOGIC;
        OV7670_XCLK  : out   STD_LOGIC;
        OV7670_D     : in    STD_LOGIC_VECTOR(7 downto 0);

        LED          : out   STD_LOGIC_VECTOR(7 downto 0);

        vga_red      : out   STD_LOGIC_VECTOR(3 downto 0);
        vga_green    : out   STD_LOGIC_VECTOR(3 downto 0);
        vga_blue     : out   STD_LOGIC_VECTOR(3 downto 0);
        vga_hsync    : out   STD_LOGIC;
        vga_vsync    : out   STD_LOGIC;

        btn          : in    STD_LOGIC;

        filter_mode : in STD_LOGIC_VECTOR(7 downto 0)
    );
end ov7670_top;

architecture Behavioral of ov7670_top is

    -- Debounces the push button.
    -- In this design, the button is used to resend/restart the camera
    -- configuration register sequence.
    COMPONENT debounce
    PORT (
        clk : IN  STD_LOGIC;
        i   : IN  STD_LOGIC;
        o   : OUT STD_LOGIC
    );
    END COMPONENT;

    -- Clock generator.
    -- Takes the board 100 MHz clock and generates:
    --   CLK_50 = 50 MHz
    --   CLK_25 = 25 MHz
    COMPONENT clocking
    PORT (
        CLK_100 : IN  STD_LOGIC;
        CLK_50  : OUT STD_LOGIC;
        CLK_25  : OUT STD_LOGIC
    );
    END COMPONENT;

    -- Sends camera configuration registers over SCCB/I2C-like bus.
    -- Also drives camera reset, power-down, and XCLK signals.
    COMPONENT ov7670_controller
    PORT (
        clk             : IN    STD_LOGIC;
        resend          : IN    STD_LOGIC;
        config_finished : OUT   STD_LOGIC;
        siod            : INOUT STD_LOGIC;
        sioc            : OUT   STD_LOGIC;
        reset           : OUT   STD_LOGIC;
        pwdn            : OUT   STD_LOGIC;
        xclk            : OUT   STD_LOGIC
    );
    END COMPONENT;

    -- Dual-port frame buffer generated from Vivado Block Memory Generator.
    --
    -- Port A:
    --   camera write side
    --   clocked by OV7670_PCLK
    --
    -- Port B:
    --   VGA read side
    --   clocked by display/read clock
    COMPONENT blk_mem_gen_0
    PORT (
        clka  : IN  STD_LOGIC;
        wea   : IN  STD_LOGIC_VECTOR(0 DOWNTO 0);
        addra : IN  STD_LOGIC_VECTOR(18 DOWNTO 0);
        dina  : IN  STD_LOGIC_VECTOR(11 DOWNTO 0);

        clkb  : IN  STD_LOGIC;
        addrb : IN  STD_LOGIC_VECTOR(18 DOWNTO 0);
        doutb : OUT STD_LOGIC_VECTOR(11 DOWNTO 0)
    );
    END COMPONENT;

    -- Captures OV7670 camera bytes and converts them into 12-bit pixels.
    -- It generates the BRAM write address, write data, and write enable.
    COMPONENT ov7670_capture
    PORT (
        pclk  : IN  STD_LOGIC;
        vsync : IN  STD_LOGIC;
        href  : IN  STD_LOGIC;
        d     : IN  STD_LOGIC_VECTOR(7 downto 0);
        addr  : OUT STD_LOGIC_VECTOR(18 downto 0);
        dout  : OUT STD_LOGIC_VECTOR(11 downto 0);
        we    : OUT STD_LOGIC
    );
    END COMPONENT;

    -- Optional frame/neighborhood filter for effects that need nearby pixels.
    -- mode:
    --   00 = pass-through
    --   01 = blur
    --   10 = sharpen
    --   11 = edge/difference
    COMPONENT frame_filter_3x3
    PORT (
        clk             : IN  STD_LOGIC;
        reset_frame     : IN  STD_LOGIC;
        mode            : IN  STD_LOGIC_VECTOR(1 downto 0);
        addr_in         : IN  STD_LOGIC_VECTOR(18 downto 0);
        pixel_in        : IN  STD_LOGIC_VECTOR(11 downto 0);
        pixel_valid_in  : IN  STD_LOGIC;
        addr_out        : OUT STD_LOGIC_VECTOR(18 downto 0);
        pixel_out       : OUT STD_LOGIC_VECTOR(11 downto 0);
        pixel_valid_out : OUT STD_LOGIC
    );
    END COMPONENT;

    -- VGA output generator.
    -- It produces VGA timing and reads pixels from the frame buffer.
    COMPONENT vga
    PORT (
        clk25       : IN  STD_LOGIC;
        vga_red     : OUT STD_LOGIC_VECTOR(3 downto 0);
        vga_green   : OUT STD_LOGIC_VECTOR(3 downto 0);
        vga_blue    : OUT STD_LOGIC_VECTOR(3 downto 0);
        vga_hsync   : OUT STD_LOGIC;
        vga_vsync   : OUT STD_LOGIC;
        frame_addr  : OUT STD_LOGIC_VECTOR(18 downto 0);
        frame_pixel : IN  STD_LOGIC_VECTOR(11 downto 0);
        filter_mode : IN  STD_LOGIC_VECTOR(7 downto 0)
    );
    END COMPONENT;

    -- Address generated by VGA module to read pixels from frame buffer.
    signal frame_addr  : STD_LOGIC_VECTOR(18 downto 0);

    -- Pixel returned from frame buffer to VGA module.
    signal frame_pixel : STD_LOGIC_VECTOR(11 downto 0);

    -- Raw camera capture stream before optional frame filtering.
    signal capture_addr_raw : STD_LOGIC_VECTOR(18 downto 0);
    signal capture_data_raw : STD_LOGIC_VECTOR(11 downto 0);
    signal capture_we_raw   : STD_LOGIC;

    -- Camera capture stream after optional frame filtering.
    signal capture_addr_filtered : STD_LOGIC_VECTOR(18 downto 0);
    signal capture_data_filtered : STD_LOGIC_VECTOR(11 downto 0);
    signal capture_we_filtered   : STD_LOGIC;

    -- BRAM write enable is a vector because Block Memory Generator expects
    -- wea as STD_LOGIC_VECTOR(0 downto 0), not a single STD_LOGIC.
    signal capture_we : STD_LOGIC_VECTOR(0 downto 0);

    -- Debounced button pulse used to restart camera register configuration.
    signal resend : STD_LOGIC;

    -- Goes high when ov7670_controller finishes sending all camera registers.
    signal config_finished : STD_LOGIC;

    -- Generated clocks.
    signal clk50 : STD_LOGIC;
    signal clk25 : STD_LOGIC;

    signal resend_combined : STD_LOGIC;
begin

    -- Debounce the physical button before using it as a resend signal.
    btn_debounce: debounce
    PORT MAP (
        clk => clk50,
        i   => btn,
        o   => resend
    );
    resend_combined <= resend or axi_resend;

    -- VGA module reads pixels from frame buffer and sends them to the monitor.
    Inst_vga: vga
    PORT MAP (
        clk25       => clk25,
        vga_red     => vga_red,
        vga_green   => vga_green,
        vga_blue    => vga_blue,
        vga_hsync   => vga_hsync,
        vga_vsync   => vga_vsync,
        frame_addr  => frame_addr,
        frame_pixel => frame_pixel,
        filter_mode => filter_mode
    );

    -- Frame buffer.
    -- Camera writes pixels into port A using OV7670_PCLK.
    -- VGA reads pixels from port B using the display/read clock.
    fb: blk_mem_gen_0
    PORT MAP (
        clka  => OV7670_PCLK,
        wea   => capture_we,
        addra => capture_addr_filtered,
        dina  => capture_data_filtered,

        -- NOTE:
        -- Your current code used clk50 here.
        -- If your VGA module advances frame_addr using clk25, the safer match is clk25.
        -- Otherwise, frame_pixel and frame_addr are in different timing domains.
        clkb  => clk25,
        addrb => frame_addr,
        doutb => frame_pixel
    );

    -- LED0 shows when camera configuration is complete.
    LED <= "0000000" & config_finished;

    -- filter_mode(7) freezes the displayed image by stopping framebuffer writes.
    -- VGA keeps reading the last complete image stored in BRAM.
    capture_we(0) <= capture_we_filtered when filter_mode(7) = '0' else '0';

    -- Camera capture block.
    -- This samples OV7670_D on OV7670_PCLK when HREF/VSYNC indicate valid video.
    -- It outputs write address/data/write-enable for the frame buffer.
    capture: ov7670_capture
    PORT MAP (
        pclk  => OV7670_PCLK,
        vsync => OV7670_VSYNC,
        href  => OV7670_HREF,
        d     => OV7670_D,
        addr  => capture_addr_raw,
        dout  => capture_data_raw,
        we    => capture_we_raw
    );

    frame_filter: frame_filter_3x3
    PORT MAP (
        clk             => OV7670_PCLK,
        reset_frame     => OV7670_VSYNC,
        mode            => filter_mode(4 downto 3),
        addr_in         => capture_addr_raw,
        pixel_in        => capture_data_raw,
        pixel_valid_in  => capture_we_raw,
        addr_out        => capture_addr_filtered,
        pixel_out       => capture_data_filtered,
        pixel_valid_out => capture_we_filtered
    );

    -- Camera controller.
    -- Sends initialization registers over OV7670_SIOC/OV7670_SIOD.
    -- Also drives OV7670_RESET, OV7670_PWDN, and OV7670_XCLK.
    controller: ov7670_controller
    PORT MAP (
        clk             => clk50,
        sioc            => OV7670_SIOC,
        resend          => resend_combined,
        config_finished => config_finished,
        siod            => OV7670_SIOD,
        pwdn            => OV7670_PWDN,
        reset           => OV7670_RESET,
        xclk            => OV7670_XCLK
    );

    -- Generate 50 MHz and 25 MHz clocks from the board 100 MHz clock.
    clk_gen: clocking
    PORT MAP (
        CLK_100 => clk100,
        CLK_50  => clk50,
        CLK_25  => clk25
    );

end Behavioral;
